import assert from "node:assert/strict";
import {createRuntime} from "../runtime.mjs";
import {detectProvider} from "../providers/catalog.mjs";
const r=createRuntime({routing:{preferredProviders:["nvidia","openai"]}});
r.registry.register({id:"nvidia-test",provider:"nvidia",capabilities:["chat","code"],priority:80});
r.registry.register({id:"openai-test",provider:"openai",capabilities:["chat","code"],priority:60});
assert.equal(detectProvider({baseUrl:"https://api.x.ai/v1",model:"grok"}),"xai");
assert.equal(r.policy.accepts(r.registry.models[0],{capabilities:["code"]}),true);
r.credentials.add("nvidia","test-secret-123",{label:"test"});
const lease=r.credentials.lease("nvidia");assert.equal(lease.secret,"test-secret-123");lease.report(false,"RATE_LIMIT");
r.plugins.install({id:"p1",name:"Test Plugin",version:"1.0.0",type:"skill",capabilities:["search"],instructions:"x"});
r.skills.register({id:"s1",name:"Test Skill",instructions:"Be precise."});
assert.match(r.skills.compose(["s1"]),/Be precise/);
r.mcpLifecycle.register({name:"mcp-test",capabilities:["search"],tools:[{name:"lookup"}]});
const tools = r.mcpAggregator.discover();
assert.equal(tools[0].name, "mcp-test__lookup", "qualified name must survive discovery");
assert.equal(tools[0].server, "mcp-test");
assert.equal(r.mcpAggregator.resolve(["mcp-test__lookup"]).length,1);assert.equal(r.mcpAggregator.resolve(["lookup"]).length,1);assert.equal(r.mcpAggregator.resolve(["mcp-test"]).length,1);
const plan=r.planner.plan({taskClass:"code",capabilities:["code"]});assert.equal(plan.steps.length,2);
console.log("CONNECTED CHAIN TEST: PASS");
